AWSTemplateFormatVersion: 2010-09-09
Description: select KeyName parameter demo

Parameters:
  MyKeyName:
    Description: select the key name from the list
    Type: AWS::EC2::KeyPair::KeyName

Resources: 
  DevEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-062f7200baf2fa504
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: my new SSH SG
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0


          